const colors = require("tailwindcss/colors")
const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
  mode: "jit",
  purge: ["./public/**/*.html", "./src/**/*.tsx", "src/**/*.ts"],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: ["ui-sans-serif", ...defaultTheme.fontFamily.sans],
      serif: ["ui-serif", "Georgia"],
      mono: ["ui-monospace", "SFMono-Regular"],
    },
    extend: {
      colors: {
        teal: colors.teal,
        transparent: "transparent",
        current: "currentColor",
        black: colors.black,
        white: colors.white,
        rose: colors.rose,
        pink: colors.pink,
        fuchsia: colors.fuchsia,
        purple: colors.purple,
        violet: colors.violet,
        indigo: colors.indigo,
        blue: colors.blue,
        sky: colors.sky,
        cyan: colors.cyan,
        teal: colors.teal,
        emerald: colors.emerald,
        green: colors.green,
        lime: colors.lime,
        yellow: colors.yellow,
        amber: colors.amber,
        orange: colors.orange,
        red: colors.red,
        warmGray: colors.warmGray,
        trueGray: colors.trueGray,
        gray: colors.gray,
        blueGray: colors.blueGray,
        coolGray: colors.coolGray,
        project: {
          primary: "#37a8df",
          primaryHov: "#00a2ed",
          primaryBg: "#bac1ff",
          secondary: "#2a3180",
          secondaryHov: "#222966",
        },
      },
      height: {
        192: "48rem",
        100: "25rem",
        120: "30rem",
        140: "35rem",
        160: "40rem",
        180: "45rem",
        81: "28rem",
        125: "0.125rem",
        8: "2rem",
        "1/4": "25%",
        "1/3": "33.333333%",
        "1/2": "50%",
        "2/3": "66.666667%;",
        "3/4": "75%",
      },
      width: {
        2: "0.5rem",
        4: "1rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
        "1/4": "25%",
        "1/3": "33.333333%",
        "1/2": "50%",
        "2/3": "66.666667%;",
        "3/4": "75%",
        8: "2rem",
        0.5: "0.125rem",
      },
      padding: {
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
      },
      margin: {
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
      },
      backgroundImage: {
        hero: "url('../images/fond_third-14.png')",
      },
      backgroundPosition: {
        hero: "bottom",
      },
      backgroundRepeat: {
        hero: "no-repeat",
      },
      backgroundSize: {
        hero: "cover",
      },
      backgroundAttachment: {
        hero: "local",
      },
      zIndex: {
        9999: "9999",
      },
      transitionProperty: {
        height: "height",
        spacing: "margin, padding",
      },
      transform: ["hover", "focus"],
      translate: {
        5: "1.25rem;",
        15: "0.375rem;",
        "-5": "-0.125rem;",
        "-15": "-0.375rem;",
      },
      spacing: {
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
      },
      typography(theme) {
        return {
          dark: {
            css: {
              color: theme("colors.gray.300"),
              '[class~="lead"]': { color: theme("colors.gray.400") },
              a: { color: theme("colors.gray.100") },
              strong: { color: theme("colors.gray.100") },
              "ul > li::before": { backgroundColor: theme("colors.gray.700") },
              hr: { borderColor: theme("colors.gray.800") },
              blockquote: {
                color: theme("colors.gray.100"),
                borderLeftColor: theme("colors.gray.800"),
              },
              h1: { color: theme("colors.gray.100") },
              h2: { color: theme("colors.gray.100") },
              h3: { color: theme("colors.gray.100") },
              h4: { color: theme("colors.gray.100") },
              p: { color: theme("color.gray.400") },
              code: { color: theme("colors.gray.100") },
              "a code": { color: theme("colors.gray.100") },
              pre: {
                color: theme("colors.gray.200"),
                backgroundColor: theme("colors.gray.800"),
              },
              thead: {
                color: theme("colors.gray.100"),
                borderBottomColor: theme("colors.gray.700"),
              },
              "tbody tr": { borderBottomColor: theme("colors.gray.800") },
            },
          },
        }
      },
    },
  },
  variants: {
    extend: {
      display: ["group-hover", "hover", "focus"],
      height: ["responsive", "group-hover", "hover", "focus"],
    },
  },
  plugins: [require("@tailwindcss/typography")],
}
